FROM golang:1.20 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/main.go .
COPY pkg/ ./pkg/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o redirect-server .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/redirect-server .
EXPOSE 8080
CMD ["./redirect-server"]